# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import dbm_pb2 as dbm__pb2


class DatabaseManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OpenDatabase = channel.unary_unary(
                '/dbmanager.DatabaseManager/OpenDatabase',
                request_serializer=dbm__pb2.OpenDatabaseRequest.SerializeToString,
                response_deserializer=dbm__pb2.Database.FromString,
                )
        self.IntersectTables = channel.unary_unary(
                '/dbmanager.DatabaseManager/IntersectTables',
                request_serializer=dbm__pb2.IntersectTablesRequest.SerializeToString,
                response_deserializer=dbm__pb2.Table.FromString,
                )


class DatabaseManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def OpenDatabase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IntersectTables(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DatabaseManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OpenDatabase': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenDatabase,
                    request_deserializer=dbm__pb2.OpenDatabaseRequest.FromString,
                    response_serializer=dbm__pb2.Database.SerializeToString,
            ),
            'IntersectTables': grpc.unary_unary_rpc_method_handler(
                    servicer.IntersectTables,
                    request_deserializer=dbm__pb2.IntersectTablesRequest.FromString,
                    response_serializer=dbm__pb2.Table.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dbmanager.DatabaseManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DatabaseManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def OpenDatabase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dbmanager.DatabaseManager/OpenDatabase',
            dbm__pb2.OpenDatabaseRequest.SerializeToString,
            dbm__pb2.Database.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def IntersectTables(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dbmanager.DatabaseManager/IntersectTables',
            dbm__pb2.IntersectTablesRequest.SerializeToString,
            dbm__pb2.Table.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
