# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dbm.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tdbm.proto\x12\tdbmanager\">\n\x16IntersectTablesRequest\x12\n\n\x02\x64\x62\x18\x01 \x01(\t\x12\x0b\n\x03tb1\x18\x02 \x01(\t\x12\x0b\n\x03tb2\x18\x03 \x01(\t\"#\n\x13OpenDatabaseRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\":\n\x08\x44\x61tabase\x12\x0c\n\x04name\x18\x01 \x01(\t\x12 \n\x06tables\x18\x02 \x03(\x0b\x32\x10.dbmanager.Table\"a\n\x05Table\x12\x0c\n\x04name\x18\x01 \x01(\t\x12 \n\x06\x66ields\x18\x02 \x03(\x0b\x32\x10.dbmanager.Field\x12\x1c\n\x04rows\x18\x03 \x03(\x0b\x32\x0e.dbmanager.Row\x12\n\n\x02id\x18\x04 \x01(\x05\"#\n\x05\x46ield\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\"*\n\x03Row\x12#\n\x06values\x18\x01 \x03(\x0b\x32\x13.dbmanager.KeyValue\"&\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t2\x9e\x01\n\x0f\x44\x61tabaseManager\x12\x43\n\x0cOpenDatabase\x12\x1e.dbmanager.OpenDatabaseRequest\x1a\x13.dbmanager.Database\x12\x46\n\x0fIntersectTables\x12!.dbmanager.IntersectTablesRequest\x1a\x10.dbmanager.Tableb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dbm_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INTERSECTTABLESREQUEST']._serialized_start=24
  _globals['_INTERSECTTABLESREQUEST']._serialized_end=86
  _globals['_OPENDATABASEREQUEST']._serialized_start=88
  _globals['_OPENDATABASEREQUEST']._serialized_end=123
  _globals['_DATABASE']._serialized_start=125
  _globals['_DATABASE']._serialized_end=183
  _globals['_TABLE']._serialized_start=185
  _globals['_TABLE']._serialized_end=282
  _globals['_FIELD']._serialized_start=284
  _globals['_FIELD']._serialized_end=319
  _globals['_ROW']._serialized_start=321
  _globals['_ROW']._serialized_end=363
  _globals['_KEYVALUE']._serialized_start=365
  _globals['_KEYVALUE']._serialized_end=403
  _globals['_DATABASEMANAGER']._serialized_start=406
  _globals['_DATABASEMANAGER']._serialized_end=564
# @@protoc_insertion_point(module_scope)
