Get database
Get database by its name
---
definitions:
  field:
    type: object
    properties:
      name:
        type: string
      type:
        type: string
  table:
    type: object
    properties:
      name:
        type: string
      id:
        type: number
      fields:
        type: array
        items:
          $ref: "#definitions/field"
      rows:
        type: array
        items:
          type: object
          additionalProperties:
            type: string

  database:
    type: object
    properties:
      name:
        type: string
      id:
        type: string
      isSaved:
        type: boolean
      tables:
        type: array
        items:
          $ref: "#/definitions/table"
responses:
  200:
    description: A database
    schema:
      $ref: "#/definitions/database"
    examples:
      databases: {}
